### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by minaslater** [DoodlingDev/key-motion#1]
[Enter steps to reproduce:]

1. command-P to open keymotion
2. error message pops up

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.4
**Thrown From**: [key-motion](https://github.com/DoodlingDev/key-motion) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

```
At /Users/minaslater/.atom/packages/key-motion/lib/key-flag.js:18

TypeError: Cannot read property 'toUpperCase' of undefined
    at KeyFlag.generateFlagDiv (/packages/key-motion/lib/key-flag.js:18:39)
    at /packages/key-motion/lib/key-flag.js:11:22)
    at /packages/key-motion/lib/key-motion.js:109:18
    at Array.forEach (<anonymous>)
    at generateFlags (/packages/key-motion/lib/key-motion.js:107:16)
    at trigger (/packages/key-motion/lib/key-motion.js:52:5)
    at HTMLElement.keymotionNav (/packages/key-motion/lib/key-motion.js:18:30)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:11.2.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -1:10.9.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -1:07.7.0 settings-view:open (input.hidden-input)
 10x -0:57.3.0 core:backspace (input.hidden-input)
     -0:10.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.4.0 core:confirm (input.hidden-input)
     -0:06.4.0 keymotion:nav (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
key-motion 0.1.0 
vim-mode-plus 1.32.0 
```

**Comment by DoodlingDev** [comment]
fixed with https://github.com/DoodlingDev/key-motion/commit/0a98489622195a39199cf6dffc0e40f8347d0db1
